create table if not exists public.ai_requests (
  id uuid primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  usage_date date not null,
  context_type text not null check (context_type in ('lesson', 'project')),
  language text not null check (language in ('en', 'so', 'ar')),
  status text not null default 'pending' check (status in ('pending', 'succeeded', 'failed')),
  provider text check (provider in ('gemini', 'groq', 'openrouter')),
  model text,
  error_code text,
  response_time_ms integer check (response_time_ms is null or response_time_ms >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists ai_requests_user_date_idx
  on public.ai_requests (user_id, usage_date desc);

create table if not exists public.ai_provider_attempts (
  id bigint generated by default as identity primary key,
  request_id uuid not null references public.ai_requests (id) on delete cascade,
  provider text not null check (provider in ('gemini', 'groq', 'openrouter')),
  model text not null,
  status text not null check (status in ('succeeded', 'failed')),
  error_code text,
  response_time_ms integer not null check (response_time_ms >= 0),
  created_at timestamptz not null default now()
);

create index if not exists ai_provider_attempts_request_idx
  on public.ai_provider_attempts (request_id);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.ai_usage'::regclass
      and contype = 'u'
      and pg_get_constraintdef(oid) = 'UNIQUE (user_id, usage_date)'
  ) then
    alter table public.ai_usage
      add constraint ai_usage_unique_user_date unique (user_id, usage_date);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conrelid = 'public.ai_usage'::regclass
      and contype = 'c'
      and pg_get_constraintdef(oid) like '%question_count >= 0%'
  ) then
    alter table public.ai_usage
      add constraint ai_usage_question_count_check check (question_count >= 0);
  end if;
end;
$$;

alter table public.ai_usage enable row level security;
alter table public.ai_requests enable row level security;
alter table public.ai_provider_attempts enable row level security;
revoke all on public.ai_usage, public.ai_requests, public.ai_provider_attempts
  from public, anon, authenticated;

grant usage on schema public to authenticated;

create or replace function public.get_ai_usage(p_daily_limit integer)
returns table (usage_date date, question_count integer, daily_limit integer, remaining_count integer)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := auth.uid();
  today_utc date := timezone('utc', now())::date;
  used_count integer := 0;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_daily_limit is distinct from 5 then
    raise exception 'Invalid AI daily limit' using errcode = '22023';
  end if;

  select coalesce((
    select au.question_count
    from public.ai_usage as au
    where au.user_id = current_user_id
      and au.usage_date = today_utc
  ), 0) into used_count;

  return query
  select today_utc, used_count, 5, greatest(5 - used_count, 0);
end;
$$;

drop function if exists public.reserve_ai_question(integer);

create or replace function public.reserve_ai_question(
  p_daily_limit integer,
  p_request_id uuid,
  p_context_type text,
  p_language text
)
returns table (
  request_id uuid,
  usage_date date,
  question_count integer,
  daily_limit integer,
  remaining_count integer,
  allowed boolean
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
#variable_conflict use_column
declare
  current_user_id uuid := auth.uid();
  today_utc date := timezone('utc', now())::date;
  used_count integer;
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_daily_limit is distinct from 5 or p_request_id is null then
    raise exception 'Invalid AI quota reservation' using errcode = '22023';
  end if;
  if p_context_type not in ('lesson', 'project') or p_language not in ('en', 'so', 'ar') then
    raise exception 'Invalid AI request context' using errcode = '22023';
  end if;

  insert into public.ai_usage as au (user_id, usage_date, question_count)
  values (current_user_id, today_utc, 1)
  on conflict (user_id, usage_date) do update
    set question_count = au.question_count + 1,
        updated_at = now()
    where au.question_count < p_daily_limit
  returning au.question_count into used_count;

  if used_count is null then
    select au.question_count into used_count
    from public.ai_usage as au
    where au.user_id = current_user_id
      and au.usage_date = today_utc;

    return query
    select null::uuid, today_utc, coalesce(used_count, 0), p_daily_limit,
      greatest(p_daily_limit - coalesce(used_count, 0), 0), false;
    return;
  end if;

  insert into public.ai_requests (id, user_id, usage_date, context_type, language)
  values (p_request_id, current_user_id, today_utc, p_context_type, p_language);

  return query
  select p_request_id, today_utc, used_count, p_daily_limit,
    greatest(p_daily_limit - used_count, 0), true;
end;
$$;

create or replace function public.finalize_ai_request(
  p_request_id uuid,
  p_status text,
  p_provider text,
  p_model text,
  p_error_code text,
  p_response_time_ms integer,
  p_attempts jsonb
)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  current_user_id uuid := auth.uid();
begin
  if current_user_id is null then
    raise exception 'Authentication required' using errcode = '28000';
  end if;
  if p_status not in ('succeeded', 'failed') or p_response_time_ms < 0 then
    raise exception 'Invalid AI request outcome' using errcode = '22023';
  end if;
  if p_provider is not null and p_provider not in ('gemini', 'groq', 'openrouter') then
    raise exception 'Invalid AI provider' using errcode = '22023';
  end if;
  if jsonb_typeof(coalesce(p_attempts, '[]'::jsonb)) <> 'array' then
    raise exception 'Invalid AI provider attempts' using errcode = '22023';
  end if;

  update public.ai_requests as request
  set status = p_status,
      provider = p_provider,
      model = p_model,
      error_code = p_error_code,
      response_time_ms = p_response_time_ms,
      updated_at = now()
  where request.id = p_request_id
    and request.user_id = current_user_id
    and request.status = 'pending';

  if not found then
    raise exception 'Pending AI request not found' using errcode = 'P0002';
  end if;

  if exists (
    select 1
    from jsonb_to_recordset(coalesce(p_attempts, '[]'::jsonb)) as attempt(
      provider text, model text, status text, error_code text, response_time_ms integer
    )
    where attempt.provider not in ('gemini', 'groq', 'openrouter')
       or attempt.status not in ('succeeded', 'failed')
       or attempt.response_time_ms is null
       or attempt.response_time_ms < 0
  ) then
    raise exception 'Invalid AI provider attempt data' using errcode = '22023';
  end if;

  insert into public.ai_provider_attempts (
    request_id, provider, model, status, error_code, response_time_ms
  )
  select
    p_request_id,
    attempt.provider,
    attempt.model,
    attempt.status,
    attempt.error_code,
    attempt.response_time_ms
  from jsonb_to_recordset(coalesce(p_attempts, '[]'::jsonb)) as attempt(
    provider text, model text, status text, error_code text, response_time_ms integer
  );

  return true;
end;
$$;

alter function public.get_ai_usage(integer) security definer;
alter function public.get_ai_usage(integer) set search_path = public, pg_temp;
alter function public.reserve_ai_question(integer, uuid, text, text) security definer;
alter function public.reserve_ai_question(integer, uuid, text, text) set search_path = public, pg_temp;

revoke all on function public.get_ai_usage(integer) from public, anon;
grant execute on function public.get_ai_usage(integer) to authenticated;
revoke all on function public.reserve_ai_question(integer, uuid, text, text) from public, anon;
grant execute on function public.reserve_ai_question(integer, uuid, text, text) to authenticated;
revoke all on function public.finalize_ai_request(uuid, text, text, text, text, integer, jsonb)
  from public, anon;
grant execute on function public.finalize_ai_request(uuid, text, text, text, text, integer, jsonb)
  to authenticated;

notify pgrst, 'reload schema';
